### ISSUE TITLE
Edit me on github" badge

### ISSUE THREAD

**Issue by mh21** [exporl/apex3-documentation#2]
For the rendered pages at https://exporl.github.io/apex3-documentation, would it be possible to get one of these fancy "Edit me on github" badges in the top-right corner of the theme that directly links to the inline editor for the .md file on github (e.g. https://github.com/exporl/apex3-documentation/edit/master/contribute/index.md)?

**Comment by Gundersanne** [comment]
Of course, I'll get on it tomorrow.

**Comment by mh21** [comment]
- delete apex latex doc
- include documentation as apex submodule
- check on jenkins that we never accept outdated documentation to apex

**Comment by Gundersanne** [comment]
change 2580/2581/2582
